FROM library/postgres

# Install.
# COPY init.sql /docker-entrypoint-initdb.d/

# RUN psql --command "CREATE USER docker WITH SUPERUSER PASSWORD 'postgres';"
# ENV POSTGRES_PASSWORD testpassword
# ENV POSTGRES_DB mission