# Use postgres/example user/password credentials
version: '3.3'

services:
  postgdb:
    build: docker/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: missions
    ports:
      - 5555:5432

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgdb