# Use postgres/example user/password credentials
version: '3.3'

services:
  postgdb:
    build: docker/postgres
    restart: always
    volumes:
    - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: missions
    expose:
      - 5432

  web:
    build: .
    command: bash -c " ./entry_for_web_container.sh"
    volumes:
      - .:/myapp
    environment:
      - PGPASSWORD=example
      - POSTGRES_PASSWORD=example
      - PGUSER=postgres
      - PGDATABASE=missions
      - PGHOST=postgdb
      - PGPORT=5432
      - RAILS_ENV=development
      - RAILS_CI=true
    ports:
      - "3000:3000"
    links:
      - postgdb
    depends_on:
      - postgdb
