# Use postgres/example user/password credentials
version: '3.3'

services:
  postgdb:
    build: docker/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: missions
    ports:
      - 5555:5432