# Use postgres/example user/password credentials
version: '3.3'

services:
  postgdb:
    build: docker/postgres
    restart: always
    volumes:
    - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: missions
    expose:
      - 5432

  web:
    build: .
    command: bash -c " ./wait-for-it.sh postgdb 5432 && bundle exec rails s -p 3000 -b '0.0.0.0' "
    volumes:
      - .:/myapp
    environment:
      - PGPASSWORD=example
      - POSTGRES_PASSWORD=example
      - PGUSER=postgres
      - PGDATABASE=missions
      - PGHOST=postgdb
      - PGPORT=5432
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    links:
      - postgdb
    depends_on:
      - postgdb
